### ISSUE TITLE
Add support for declared_value_set in JSIDL.

### ISSUE THREAD

**Issue by cgagner** [jaustoolset/jaustoolset#14]
Add support for declared_value_set in JSIDL.

JTS does not currently support ```declared_value_set``` in JSIDL. This has been part of the standard since JSIDL 1.0. Below is an example of how it could be used:

```xml
<value_set name="BooleanValueSet" offset_to_lower_limit="false">
    <value_enum enum_index="0" enum_const="False"/>
    <value_enum enum_index="1" enum_const="True"/>
</value_set>

<bit_field name="ResolutionSupported" field_type_unsigned="unsigned byte" optional="false">
    <sub_field name="Low" interpretation="Low resolution supported.">
        <bit_range from_index="0" to_index="0"/>
        <declared_value_set name="Supported" declared_type_ref="BooleanValueSet"/>
    </sub_field>
    <sub_field name="Medium" interpretation="Medium resolution supported.">
        <bit_range from_index="1" to_index="1"/>
        <declared_value_set name="Supported" declared_type_ref="BooleanValueSet"/>
    </sub_field>
    <sub_field name="High" interpretation="High resolution supported.">
        <bit_range from_index="2" to_index="2"/>
        <declared_value_set name="Supported" declared_type_ref="BooleanValueSet"/>
    </sub_field>
</bit_field>
```
Using ```declared_value_set``` causes an exception to be thrown when importing into JTS:
```
>> Import Error: Unknown JAXB object type while trying to resolve declared_type_set myTypes

>> Found 1 import errors...
Exception in thread "Thread-9" java.lang.RuntimeException: Error while importing service definitions.
	at org.jts.gui.importJSIDL.Import$ImportDefsWorker.run(Import.java:257)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.jts.gui.importJSIDL.ImportException: Unknown JAXB object type while trying to resolve declared_type_set myTypes
	at org.jts.gui.importJSIDL.Import$ImportDefsWorker.performImport(Import.java:443)
	at org.jts.gui.importJSIDL.Import$ImportDefsWorker.run(Import.java:250)
	... 1 more
Caused by: org.jts.gui.importJSIDL.ImportException: Unknown JAXB object type while trying to resolve declared_type_set myTypes
	at org.jts.gui.importJSIDL.declaredElementsResolution.DeclaredTypeSet.mapElement(DeclaredTypeSet.java:342)
	at org.jts.gui.importJSIDL.declaredElementsResolution.DeclaredTypeSet.importDeclaredTypeSet(DeclaredTypeSet.java:152)
	at org.jts.gui.importJSIDL.declaredElementsResolution.DeclaredTypeSet.importDeclaredTypeSet(DeclaredTypeSet.java:106)
	at org.jts.gui.importJSIDL.declaredElementsResolution.DeclaredTypeSet.importDeclaredTypeSet(DeclaredTypeSet.java:106)
	at org.jts.gui.importJSIDL.declaredElementsResolution.DeclaredTypeSet.importDeclaredTypeSet(DeclaredTypeSet.java:106)
	at org.jts.gui.importJSIDL.declaredElementsResolution.ServiceDef.resolveDeclaredElements(ServiceDef.java:52)
	at org.jts.gui.importJSIDL.Import$ImportDefsWorker.performImport(Import.java:436)
```

Since ```declared_value_set``` is not supported, we have to do something like this:
```xml
<bit_field name="ResolutionSupported" field_type_unsigned="unsigned byte" optional="false">
    <sub_field name="Low" interpretation="Low resolution supported.">
        <bit_range from_index="0" to_index="0"/>
        <value_set name="BooleanValueSet" offset_to_lower_limit="false">
            <value_enum enum_index="0" enum_const="False"/>
            <value_enum enum_index="1" enum_const="True"/>
        </value_set>
    </sub_field>
    <sub_field name="Medium" interpretation="Medium resolution supported.">
        <bit_range from_index="1" to_index="1"/>
        <value_set name="BooleanValueSet" offset_to_lower_limit="false">
            <value_enum enum_index="0" enum_const="False"/>
            <value_enum enum_index="1" enum_const="True"/>
        </value_set>
    </sub_field>
    <sub_field name="High" interpretation="High resolution supported.">
        <bit_range from_index="2" to_index="2"/>
        <value_set name="BooleanValueSet" offset_to_lower_limit="false">
            <value_enum enum_index="0" enum_const="False"/>
            <value_enum enum_index="1" enum_const="True"/>
        </value_set>
    </sub_field>
</bit_field>
```

**Comment by dvmartin999** [comment]
Fixed in PR 39
