### ISSUE TITLE
Failure to start GUI

### ISSUE THREAD

**Issue by bigrobinson** [jaustoolset/jaustoolset#86]
```
~/JTS/GUI$ ant run
```

Java version:
```
java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)
```

Ant  version:
```
Apache Ant(TM) version 1.10.12 compiled on January 17 1970
```

SCons Version:
```
SCons by Steven Knight et al.:
	SCons: v4.0.1.c289977f8b34786ab6c334311e232886da7e8df1, 2020-07-17 01:50:03, by bdbaddog on ProDog2020
	SCons path: ['/usr/lib/python3/dist-packages/SCons']
Copyright (c) 2001 - 2020 The SCons Foundation
```
Stack trace:
```
     [java] Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
     [java] 	at com.u2d.view.swing.EntryPoint$1.run(EntryPoint.java:48)
     [java] 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
     [java] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
     [java] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
     [java] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
     [java] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
     [java] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
     [java] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [java] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
     [java] Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
     [java] 	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:234)
     [java] 	at com.u2d.cssparser.CSSParser.imageResourceRef(CSSParser.java:2435)
     [java] 	at com.u2d.cssparser.CSSParser.imagedecl(CSSParser.java:2318)
     [java] 	at com.u2d.cssparser.CSSParser.declaration(CSSParser.java:944)
     [java] 	at com.u2d.cssparser.CSSParser.rule(CSSParser.java:358)
     [java] 	at com.u2d.cssparser.CSSParser.stylesheet(CSSParser.java:229)
     [java] 	at com.u2d.css4swing.CSSEngine.parseStylesheet(CSSEngine.java:94)
     [java] 	at com.u2d.css4swing.CSSEngine.init(CSSEngine.java:83)
     [java] 	at com.u2d.css4swing.CSSEngine.<init>(CSSEngine.java:61)
     [java] 	at com.u2d.css4swing.CSSEngine.<init>(CSSEngine.java:56)
     [java] 	at com.u2d.css4swing.CSSEngine.initialize(CSSEngine.java:50)
     [java] 	at com.u2d.view.swing.SwingViewMechanism.<init>(SwingViewMechanism.java:77)
     [java] 	at com.u2d.view.swing.SwingViewMechanism.<clinit>(SwingViewMechanism.java:67)
     [java] 	... 14 more
```

**Comment by bigrobinson** [comment]
I just forgot to invoke this ant target first:

```
~/JTS/GUI$ ant schema-export
```
